ESA CANopen Docs: src/actuator.c File Reference
actuator.c File Reference
Implementation of actuator cache layer for CiA-402 over CANopen (RPDO1/TPDO1).
#include "actuator.h"
Functions
void actuator_init (void)
Initialize actuator module (zero both caches).
void actuator_master_set_controlword (uint16_t cw)
Set master-side Controlword (0x6040).
void actuator_master_set_target_pos (int32_t pos)
Set master-side Target position (0x607A).
uint16_t actuator_master_get_controlword (void)
Get the latest master-side Controlword (0x6040).
int32_t actuator_master_get_target_pos (void)
Get the latest master-side Target position (0x607A).
uint16_t actuator_master_get_statusword (void)
Get Statusword (0x6041) received by the master.
int32_t actuator_master_get_pos_actual (void)
Get Position actual value (0x6064) received by the master.
int actuator_master_tx_update (void)
Transmit master RPDO1 (Controlword + Target position).
void actuator_master_rx_update (uint32_t cob_id, const uint8_t *data, uint8_t len)
Process a received CAN frame on the master side (TPDO1).
uint16_t actuator_slave_get_controlword (void)
Get slave-side Controlword (0x6040) received via RPDO1.
int32_t actuator_slave_get_target_pos (void)
Get slave-side Target position (0x607A) received via RPDO1.
void actuator_slave_set_statusword (uint16_t sw)
Set slave-side Statusword (0x6041) to be transmitted in TPDO1.
void actuator_slave_set_pos_actual (int32_t act_pos)
Set slave-side Position actual value (0x6064) to be transmitted in TPDO1.
uint16_t actuator_slave_get_statusword (void)
Get slave-side Statusword (0x6041) from the local cache.
int32_t actuator_slave_get_pos_actual (void)
Get slave-side Position actual value (0x6064) from the local cache.
void actuator_slave_rx_update (uint32_t ms)
Update slave receive path (RPDO1 -> OD -> wrapper -> cache).
void actuator_slave_tx_update (void)
Update slave transmit path (cache -> wrapper -> OD -> TPDO1 event).
Variables
static Actuator_t g_master = {0}
Local master-side cache.
static Actuator_t g_slave = {0}
Local slave-side cache.
Detailed Description
Implementation of actuator cache layer for CiA-402 over CANopen (RPDO1/TPDO1).
This module keeps a local cache for both MASTER and SLAVE roles:
MASTER: set Controlword (0x6040) + Target position (0x607A), transmit RPDO1, parse TPDO1 (Statusword 0x6041 + Position actual 0x6064).
SLAVE : receive CW/Target via OD pull (RPDO1 mapped objects), transmit SW/ActualPos via OD push + TPDO event.
The actual node_id/bus_id configuration and PDO mapping are handled by cia402_wrapper.
Definition in file actuator.c.
Function Documentation
actuator_init()
void actuator_init (void)
Initialize actuator module (zero both caches).
Initialize actuator module (zero the caches).
Note
This function does NOT configure node_id/bus_id. Do that elsewhere via cia402_wrapper (e.g. set role, node_id, bus_id, PDO mapping).
Definition at line 26 of file actuator.c.
References g_master, and g_slave.
actuator_master_get_controlword()
uint16_t actuator_master_get_controlword (void)
Get the latest master-side Controlword (0x6040).
Reads from the wrapper as the source of truth and updates the cache.
Returns
Controlword (0x6040).
Definition at line 71 of file actuator.c.
References cia402_master_get_controlword(), Actuator_t::cw, and g_master.
actuator_master_get_pos_actual()
int32_t actuator_master_get_pos_actual (void)
Get Position actual value (0x6064) received by the master.
The value is updated when TPDO1 is received and actuator_master_rx_update() has been called.
Returns
Position actual value (0x6064).
Definition at line 112 of file actuator.c.
References Actuator_t::act_pos, cia402_master_get_pos_actual(), and g_master.
actuator_master_get_statusword()
uint16_t actuator_master_get_statusword (void)
Get Statusword (0x6041) received by the master.
Statusword is updated when TPDO1 is received and actuator_master_rx_update() has been called.
Returns
Statusword (0x6041).
Definition at line 98 of file actuator.c.
References cia402_master_get_statusword(), g_master, and Actuator_t::sw.
actuator_master_get_target_pos()
int32_t actuator_master_get_target_pos (void)
Get the latest master-side Target position (0x607A).
Reads from the wrapper as the source of truth and updates the cache.
Returns
Target position (0x607A).
Definition at line 84 of file actuator.c.
References cia402_master_get_target_pos(), g_master, and Actuator_t::pos.
actuator_master_rx_update()
void actuator_master_rx_update (uint32_t cob_id, const uint8_t * data, uint8_t len)
Process a received CAN frame on the master side (TPDO1).
The frame is forwarded to the wrapper parser. If it matches TPDO1 for the configured node (typically COB-ID = 0x180 + node, mapping 0x6041:16 + 0x6064:32), the wrapper updates its values and this module pulls them into the master cache.
Parameters
cob_id CAN identifier (COB-ID).
data Payload pointer.
len Payload length (expected 6 bytes for 16+32 mapping).
Definition at line 143 of file actuator.c.
References Actuator_t::act_pos, cia402_master_get_pos_actual(), cia402_master_get_statusword(), cia402_master_pdo_parse_tpdo1(), g_master, and Actuator_t::sw.
actuator_master_set_controlword()
void actuator_master_set_controlword (uint16_t cw)
Set master-side Controlword (0x6040).
Stores the value in the master cache and forwards it to the CiA-402 wrapper. The frame is not put on the bus until actuator_master_tx_update() is called.
Parameters
cw Controlword value (e.g. Shutdown/Switch on/Enable operation).
Definition at line 45 of file actuator.c.
References cia402_master_set_controlword(), Actuator_t::cw, and g_master.
actuator_master_set_target_pos()
void actuator_master_set_target_pos (int32_t pos)
Set master-side Target position (0x607A).
Stores the value in the master cache and forwards it to the CiA-402 wrapper. The frame is not put on the bus until actuator_master_tx_update() is called.
Parameters
pos Target position (units depend on your drive configuration).
Definition at line 58 of file actuator.c.
References cia402_master_set_target_pos(), g_master, and Actuator_t::pos.
actuator_master_tx_update()
int actuator_master_tx_update (void)
Transmit master RPDO1 (Controlword + Target position).
Performs an RPDO1 “flush” configured in the wrapper: mapping: 0x6040:16 + 0x607A:32 (typically RPDO1 COB-ID = 0x200 + node).
Return values
0 Success.
<0 Error from wrapper/stack.
Definition at line 127 of file actuator.c.
References cia402_master_pdo_flush_rpdo1().
actuator_slave_get_controlword()
uint16_t actuator_slave_get_controlword (void)
Get slave-side Controlword (0x6040) received via RPDO1.
Expects that actuator_slave_rx_update() has been called earlier (OD pull).
Returns
Controlword (0x6040).
Definition at line 161 of file actuator.c.
References cia402_actuator_get_controlword(), Actuator_t::cw, and g_slave.
actuator_slave_get_pos_actual()
int32_t actuator_slave_get_pos_actual (void)
Get slave-side Position actual value (0x6064) from the local cache.
On the slave side, actual position is typically produced by the application and written via actuator_slave_set_pos_actual().
Returns
Cached Position actual value (0x6064).
Definition at line 226 of file actuator.c.
References Actuator_t::act_pos, and g_slave.
actuator_slave_get_statusword()
uint16_t actuator_slave_get_statusword (void)
Get slave-side Statusword (0x6041) from the local cache.
On the slave side, Statusword is typically produced by the application (state machine) and written via actuator_slave_set_statusword().
Returns
Cached Statusword (0x6041).
Definition at line 214 of file actuator.c.
References g_slave, and Actuator_t::sw.
actuator_slave_get_target_pos()
int32_t actuator_slave_get_target_pos (void)
Get slave-side Target position (0x607A) received via RPDO1.
Expects that actuator_slave_rx_update() has been called earlier (OD pull).
Returns
Target position (0x607A).
Definition at line 174 of file actuator.c.
References cia402_actuator_get_target_pos(), g_slave, and Actuator_t::pos.
actuator_slave_rx_update()
void actuator_slave_rx_update (uint32_t ms)
Update slave receive path (RPDO1 -> OD -> wrapper -> cache).
Performs OD pull of the RPDO1-mapped objects (Controlword + Target position) and updates the slave cache accordingly. Call this periodically (e.g. every 1 ms) from your main loop or timer tick.
Parameters
ms Current time in milliseconds (used by the underlying stack for timing).
Definition at line 239 of file actuator.c.
References cia402_actuator_get_controlword(), cia402_actuator_get_target_pos(), cia402_actuator_pdo_pull_rpdo1_from_od(), Actuator_t::cw, g_slave, and Actuator_t::pos.
actuator_slave_set_pos_actual()
void actuator_slave_set_pos_actual (int32_t act_pos)
Set slave-side Position actual value (0x6064) to be transmitted in TPDO1.
Stores the value in the slave cache and forwards it to the wrapper. Actual TPDO1 transmit happens when actuator_slave_tx_update() is called.
Parameters
act_pos Position actual value (0x6064).
Definition at line 201 of file actuator.c.
References Actuator_t::act_pos, cia402_actuator_set_pos_actual(), and g_slave.
actuator_slave_set_statusword()
void actuator_slave_set_statusword (uint16_t sw)
Set slave-side Statusword (0x6041) to be transmitted in TPDO1.
Stores the value in the slave cache and forwards it to the wrapper. Actual TPDO1 transmit happens when actuator_slave_tx_update() is called.
Parameters
sw Statusword (0x6041).
Definition at line 187 of file actuator.c.
References cia402_actuator_set_statusword(), g_slave, and Actuator_t::sw.
actuator_slave_tx_update()
void actuator_slave_tx_update (void)
Update slave transmit path (cache -> wrapper -> OD -> TPDO1 event).
Ensures the latest Statusword and Position actual value are present in the wrapper, pushes them into the OD and triggers TPDO1 transmission (event-driven TPDO). Call this whenever you want to publish new feedback to the master.
Definition at line 252 of file actuator.c.
References Actuator_t::act_pos, cia402_actuator_pdo_push_tpdo1_to_od_and_send(), cia402_actuator_set_pos_actual(), cia402_actuator_set_statusword(), g_slave, and Actuator_t::sw.
Variable Documentation
g_master
Actuator_t g_master = {0} static
Local master-side cache.
Definition at line 16 of file actuator.c.
Referenced by actuator_init(), actuator_master_get_controlword(), actuator_master_get_pos_actual(), actuator_master_get_statusword(), actuator_master_get_target_pos(), actuator_master_rx_update(), actuator_master_set_controlword(), and actuator_master_set_target_pos().
g_slave
Actuator_t g_slave = {0} static
Local slave-side cache.
Definition at line 18 of file actuator.c.
Referenced by actuator_init(), actuator_slave_get_controlword(), actuator_slave_get_pos_actual(), actuator_slave_get_statusword(), actuator_slave_get_target_pos(), actuator_slave_rx_update(), actuator_slave_set_pos_actual(), actuator_slave_set_statusword(), and actuator_slave_tx_update().