ESA CANopen Docs: inc/canopen_space.h File Reference
canopen_space.h File Reference
Lightweight CANopen/Lely-core “space” wrapper (init/start/tick/rx/tx helpers).
#include <lely/config.h>
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <lely/can/msg.h>
#include <lely/can/net.h>
#include <lely/co/dev.h>
#include <lely/co/obj.h>
#include <lely/co/nmt.h>
#include <lely/util/error.h>
#include <lely/util/memory.h>
#include <lely/util/mempool.h>
#include <string.h>
#include <lely/co/rpdo.h>
#include <lely/co/tpdo.h>
#include "od_slave_pdo.h"
#include "od_master_pdo.h"
Data Structures
struct canopen_space_cfg_t
Configuration passed to canopen_space_init().
struct canopen_space_ctx_t
Global context of the canopen_space instance.
Typedefs
typedef int(* canopen_space_send_func_t) (uint_least8_t bus_id, const struct can_msg *msg, void *user)
User-provided CAN send callback.
Enumerations
enum canopen_space_role_t { CO_ROLE_MASTER = 0 , CO_ROLE_ACTUATOR = 1 }
Runtime role of the stack instance.
Functions
int canopen_space_init (const canopen_space_cfg_t *cfg)
Initialize the CANopen/Lely stack instance using the provided configuration.
int canopen_space_start (void)
Start the stack services depending on role.
void canopen_space_tick_1ms (void)
Advance stack time by 1 ms (must be called every 1 ms).
void canopen_space_on_rx (uint_least8_t bus_id, uint32_t id, bool ext, bool rtr, const uint8_t *data, uint8_t len)
Feed an incoming CAN frame into the Lely stack.
co_dev_t * canopen_space_dev (void)
Get pointer to the initialized Object Dictionary (OD).
co_nmt_t * canopen_space_nmt (void)
Get pointer to the NMT object.
co_tpdo_t * canopen_space_tpdo1 (void)
Get pointer to TPDO1 (actuator role).
co_rpdo_t * canopen_space_rpdo1 (void)
Get pointer to RPDO1 (actuator role).
int canopen_space_sdo_write_u32 (uint8_t bus_id, uint8_t node_id, uint16_t idx, uint8_t sub, uint32_t val)
Send an expedited SDO download (u32) to a node (COB-ID 0x600 + node_id).
int canopen_space_send_raw (uint_least8_t bus_id, uint32_t id, bool ext, bool rtr, const uint8_t *data, uint8_t len)
Send a raw CAN frame using the user TX callback.
Detailed Description
Lightweight CANopen/Lely-core “space” wrapper (init/start/tick/rx/tx helpers).
This module wraps a minimal subset of Lely-core CANopen stack to be used on bare-metal targets (STM32) with an external transport callback for CAN TX.
Responsibilities:
Create and configure Lely objects: can_net, co_dev (OD), co_nmt.
Provide 1ms timebase integration (canopen_space_tick_1ms()).
Feed received CAN frames into the stack (canopen_space_on_rx()).
Optionally create RPDO1/TPDO1 objects on ACTUATOR role and configure PDO mapping runtime.
Provide raw CAN send helper and a simple SDO write helper (expedited u32).
The OD itself is provided by generated headers:
od_slave_pdo.h / od_master_pdo.h
Definition in file canopen_space.h.
Typedef Documentation
canopen_space_send_func_t
typedef int(* canopen_space_send_func_t) (uint_least8_t bus_id, const struct can_msg *msg, void *user)
User-provided CAN send callback.
The stack calls this to transmit CAN frames via the platform driver (FDCAN, bxCAN, etc.).
Parameters
bus_id Logical bus identifier.
msg CAN frame to send (Lely can_msg).
user User context pointer (cfg->send_user).
Returns
0 on success, <0 on error.
Definition at line 57 of file canopen_space.h.
Enumeration Type Documentation
canopen_space_role_t
enum canopen_space_role_t
Runtime role of the stack instance.
Enumerator
CO_ROLE_MASTER
Node acts as CANopen master/controller.
CO_ROLE_ACTUATOR
Node acts as actuator/slave device.
Definition at line 42 of file canopen_space.h.
Function Documentation
canopen_space_dev()
co_dev_t* canopen_space_dev (void)
Get pointer to the initialized Object Dictionary (OD).
Returns
OD pointer or NULL if not initialized.
Definition at line 334 of file canopen_space.c.
References canopen_space_ctx_t::dev, and g_ctx.
Referenced by cia402_actuator_pdo_pull_rpdo1_from_od(), and cia402_actuator_pdo_push_tpdo1_to_od_and_send().
canopen_space_init()
int canopen_space_init (const canopen_space_cfg_t * cfg)
Initialize the CANopen/Lely stack instance using the provided configuration.
Creates mempool, can_net, OD (master or slave), configures heartbeat objects, creates NMT and (optionally) PDO objects for ACTUATOR role.
Parameters
cfg Pointer to init configuration.
Return values
0 Success.
<0 Parameter/initialization error.
Definition at line 132 of file canopen_space.c.
References can_next_func(), can_send_func(), CO_ROLE_ACTUATOR, canopen_space_ctx_t::dev, die(), g_ctx, canopen_space_cfg_t::mem, canopen_space_cfg_t::mem_size, canopen_space_ctx_t::net, canopen_space_ctx_t::nmt, canopen_space_cfg_t::node_id, canopen_space_ctx_t::node_id, od_init_for_role(), pdo_config_slave_runtime(), canopen_space_ctx_t::pool, canopen_space_ctx_t::pool_mem, canopen_space_ctx_t::pool_size, canopen_space_cfg_t::role, canopen_space_ctx_t::role, canopen_space_ctx_t::rpdo1, canopen_space_cfg_t::send, canopen_space_ctx_t::send, canopen_space_cfg_t::send_user, canopen_space_ctx_t::send_user, canopen_space_ctx_t::tpdo1, and canopen_space_ctx_t::ts.
canopen_space_nmt()
co_nmt_t* canopen_space_nmt (void)
Get pointer to the NMT object.
Returns
NMT pointer or NULL if not initialized.
Definition at line 342 of file canopen_space.c.
References g_ctx, and canopen_space_ctx_t::nmt.
canopen_space_on_rx()
void canopen_space_on_rx (uint_least8_t bus_id, uint32_t id, bool ext, bool rtr, const uint8_t * data, uint8_t len)
Feed an incoming CAN frame into the Lely stack.
Call this from your CAN RX interrupt/callback (after copying payload).
Parameters
bus_id Bus identifier.
id CAN identifier.
ext Extended ID flag.
rtr Remote transmission request flag.
data Payload pointer (may be NULL if len=0).
len Payload length (0..8).
Definition at line 244 of file canopen_space.c.
References g_ctx, canopen_space_ctx_t::last_rx_id, and canopen_space_ctx_t::net.
canopen_space_rpdo1()
co_rpdo_t* canopen_space_rpdo1 (void)
Get pointer to RPDO1 (actuator role).
Returns
RPDO1 pointer or NULL if not created.
Definition at line 358 of file canopen_space.c.
References g_ctx, and canopen_space_ctx_t::rpdo1.
canopen_space_sdo_write_u32()
int canopen_space_sdo_write_u32 (uint8_t bus_id, uint8_t node_id, uint16_t idx, uint8_t sub, uint32_t val)
Send an expedited SDO download (u32) to a node (COB-ID 0x600 + node_id).
Send an expedited SDO download (u32) to a node (COB-ID 0x600 + node).
Builds an 8-byte "Download Initiate" request with command specifier 0x23:
expedited transfer
size indicated
4 data bytes (u32)
Payload layout:
byte 0 : 0x23 (SDO Download Initiate, expedited, size=4)
byte 1 : index low
byte 2 : index high
byte 3 : subindex
byte 4..7 : value (little-endian)
Parameters
bus_id Bus identifier used by canopen_space transport.
node_id Destination node ID.
idx Object dictionary index.
sub Object dictionary subindex.
val 32-bit value to write.
Return values
0 Success.
<0 Transport error.
Builds an 8-byte SDO Download Initiate (0x23) frame and sends it via canopen_space_send_raw().
Parameters
bus_id Bus identifier.
node_id Destination node ID.
idx Object index.
sub Object sub-index.
val 32-bit value to write.
Returns
0 on success, <0 on error.
Definition at line 286 of file canopen_space.c.
References canopen_space_send_raw().
canopen_space_send_raw()
int canopen_space_send_raw (uint_least8_t bus_id, uint32_t id, bool ext, bool rtr, const uint8_t * data, uint8_t len)
Send a raw CAN frame using the user TX callback.
Parameters
bus_id Bus identifier.
id CAN identifier.
ext Extended ID flag.
rtr RTR flag.
data Payload pointer (may be NULL if len=0).
len Payload length (0..8).
Returns
0 on success, <0 on error.
Definition at line 313 of file canopen_space.c.
References g_ctx, canopen_space_ctx_t::last_tx_id, canopen_space_ctx_t::send, and canopen_space_ctx_t::send_user.
Referenced by canopen_space_sdo_write_u32(), and cia402_send_nmt().
canopen_space_start()
int canopen_space_start (void)
Start the stack services depending on role.
For ACTUATOR role this typically starts RPDO/TPDO objects and transitions NMT states (Reset comm -> Pre-op -> Operational). For MASTER role it performs minimal local NMT init (implementation-defined).
Returns
0 on success, <0 on error.
Definition at line 199 of file canopen_space.c.
References CO_ROLE_ACTUATOR, canopen_space_ctx_t::dev, g_ctx, canopen_space_ctx_t::net, canopen_space_ctx_t::nmt, canopen_space_ctx_t::role, canopen_space_ctx_t::rpdo1, and canopen_space_ctx_t::tpdo1.
canopen_space_tick_1ms()
void canopen_space_tick_1ms (void)
Advance stack time by 1 ms (must be called every 1 ms).
Updates internal timespec and calls can_net_set_time(). This is critical on bare-metal targets without POSIX clocks.
Definition at line 222 of file canopen_space.c.
References canopen_space_ctx_t::fail_code, g_ctx, canopen_space_ctx_t::net, time_add_1ms(), and canopen_space_ctx_t::ts.
canopen_space_tpdo1()
co_tpdo_t* canopen_space_tpdo1 (void)
Get pointer to TPDO1 (actuator role).
Returns
TPDO1 pointer or NULL if not created.
Definition at line 350 of file canopen_space.c.
References g_ctx, and canopen_space_ctx_t::tpdo1.
Referenced by cia402_actuator_pdo_push_tpdo1_to_od_and_send().