ESA CANopen Docs: src/canopen_space.c File Reference
canopen_space.c File Reference
Implementation of lightweight CANopen/Lely-core wrapper (init/start/tick/rx/tx).
#include "canopen_space.h"
Functions
static void die (uint32_t code)
Trap into a fatal error state (debug helper).
static co_dev_t * od_init_for_role (canopen_space_role_t role)
Initialize the OD depending on role (master vs actuator).
static void time_add_1ms (struct timespec *ts)
Add 1ms to timespec (bare-metal timebase).
static int can_next_func (const struct timespec *tp, void *data)
Lely "next deadline" callback (not used in this bare-metal integration).
static int can_send_func (const struct can_msg *msg, uint_least8_t bus_id, void *data)
Lely CAN send callback, forwards frames to user transport function.
static void pdo_config_slave_runtime (co_dev_t *dev, uint8_t node_id)
Configure PDO mapping for ACTUATOR at runtime (RPDO1 and TPDO1).
int canopen_space_init (const canopen_space_cfg_t *cfg)
Initialize the CANopen/Lely stack instance using the provided configuration.
int canopen_space_start (void)
Start the stack services depending on role.
void canopen_space_tick_1ms (void)
Advance stack time by 1 ms (must be called every 1 ms).
void canopen_space_on_rx (uint_least8_t bus_id, uint32_t id, bool ext, bool rtr, const uint8_t *data, uint8_t len)
Feed an incoming CAN frame into the Lely stack.
int canopen_space_sdo_write_u32 (uint8_t bus_id, uint8_t node_id, uint16_t idx, uint8_t sub, uint32_t val)
Send an expedited SDO download (u32) to a node (COB-ID 0x600 + node_id).
int canopen_space_send_raw (uint_least8_t bus_id, uint32_t id, bool ext, bool rtr, const uint8_t *data, uint8_t len)
Send a raw CAN frame using the user TX callback.
co_dev_t * canopen_space_dev (void)
Get pointer to the initialized Object Dictionary (OD).
co_nmt_t * canopen_space_nmt (void)
Get pointer to the NMT object.
co_tpdo_t * canopen_space_tpdo1 (void)
Get pointer to TPDO1 (actuator role).
co_rpdo_t * canopen_space_rpdo1 (void)
Get pointer to RPDO1 (actuator role).
Variables
static canopen_space_ctx_t g_ctx = {0}
Detailed Description
Implementation of lightweight CANopen/Lely-core wrapper (init/start/tick/rx/tx).
Definition in file canopen_space.c.
Function Documentation
can_next_func()
static int can_next_func (const struct timespec * tp, void * data) static
Lely "next deadline" callback (not used in this bare-metal integration).
tp == NULL means "no deadline". If you later integrate with a HW timer, you can use *tp here.
Definition at line 52 of file canopen_space.c.
Referenced by canopen_space_init().
can_send_func()
static int can_send_func (const struct can_msg * msg, uint_least8_t bus_id, void * data) static
Lely CAN send callback, forwards frames to user transport function.
Parameters
msg CAN frame prepared by Lely.
bus_id Bus identifier.
data Unused user data (we use g_ctx).
Returns
0 on success, <0 on error.
Definition at line 66 of file canopen_space.c.
References canopen_space_ctx_t::fail_code, g_ctx, canopen_space_ctx_t::last_tx_id, canopen_space_ctx_t::send, and canopen_space_ctx_t::send_user.
Referenced by canopen_space_init().
canopen_space_dev()
co_dev_t* canopen_space_dev (void)
Get pointer to the initialized Object Dictionary (OD).
Returns
OD pointer or NULL if not initialized.
Definition at line 334 of file canopen_space.c.
References canopen_space_ctx_t::dev, and g_ctx.
Referenced by cia402_actuator_pdo_pull_rpdo1_from_od(), and cia402_actuator_pdo_push_tpdo1_to_od_and_send().
canopen_space_init()
int canopen_space_init (const canopen_space_cfg_t * cfg)
Initialize the CANopen/Lely stack instance using the provided configuration.
Creates mempool, can_net, OD (master or slave), configures heartbeat objects, creates NMT and (optionally) PDO objects for ACTUATOR role.
Parameters
cfg Pointer to init configuration.
Return values
0 Success.
<0 Parameter/initialization error.
Definition at line 132 of file canopen_space.c.
References can_next_func(), can_send_func(), CO_ROLE_ACTUATOR, canopen_space_ctx_t::dev, die(), g_ctx, canopen_space_cfg_t::mem, canopen_space_cfg_t::mem_size, canopen_space_ctx_t::net, canopen_space_ctx_t::nmt, canopen_space_cfg_t::node_id, canopen_space_ctx_t::node_id, od_init_for_role(), pdo_config_slave_runtime(), canopen_space_ctx_t::pool, canopen_space_ctx_t::pool_mem, canopen_space_ctx_t::pool_size, canopen_space_cfg_t::role, canopen_space_ctx_t::role, canopen_space_ctx_t::rpdo1, canopen_space_cfg_t::send, canopen_space_ctx_t::send, canopen_space_cfg_t::send_user, canopen_space_ctx_t::send_user, canopen_space_ctx_t::tpdo1, and canopen_space_ctx_t::ts.
canopen_space_nmt()
co_nmt_t* canopen_space_nmt (void)
Get pointer to the NMT object.
Returns
NMT pointer or NULL if not initialized.
Definition at line 342 of file canopen_space.c.
References g_ctx, and canopen_space_ctx_t::nmt.
canopen_space_on_rx()
void canopen_space_on_rx (uint_least8_t bus_id, uint32_t id, bool ext, bool rtr, const uint8_t * data, uint8_t len)
Feed an incoming CAN frame into the Lely stack.
Call this from your CAN RX interrupt/callback (after copying payload).
Parameters
bus_id Bus identifier.
id CAN identifier.
ext Extended ID flag.
rtr Remote transmission request flag.
data Payload pointer (may be NULL if len=0).
len Payload length (0..8).
Definition at line 244 of file canopen_space.c.
References g_ctx, canopen_space_ctx_t::last_rx_id, and canopen_space_ctx_t::net.
canopen_space_rpdo1()
co_rpdo_t* canopen_space_rpdo1 (void)
Get pointer to RPDO1 (actuator role).
Returns
RPDO1 pointer or NULL if not created.
Definition at line 358 of file canopen_space.c.
References g_ctx, and canopen_space_ctx_t::rpdo1.
canopen_space_sdo_write_u32()
int canopen_space_sdo_write_u32 (uint8_t bus_id, uint8_t node_id, uint16_t idx, uint8_t sub, uint32_t val)
Send an expedited SDO download (u32) to a node (COB-ID 0x600 + node_id).
Builds an 8-byte "Download Initiate" request with command specifier 0x23:
expedited transfer
size indicated
4 data bytes (u32)
Payload layout:
byte 0 : 0x23 (SDO Download Initiate, expedited, size=4)
byte 1 : index low
byte 2 : index high
byte 3 : subindex
byte 4..7 : value (little-endian)
Parameters
bus_id Bus identifier used by canopen_space transport.
node_id Destination node ID.
idx Object dictionary index.
sub Object dictionary subindex.
val 32-bit value to write.
Return values
0 Success.
<0 Transport error.
Definition at line 286 of file canopen_space.c.
References canopen_space_send_raw().
canopen_space_send_raw()
int canopen_space_send_raw (uint_least8_t bus_id, uint32_t id, bool ext, bool rtr, const uint8_t * data, uint8_t len)
Send a raw CAN frame using the user TX callback.
Parameters
bus_id Bus identifier.
id CAN identifier.
ext Extended ID flag.
rtr RTR flag.
data Payload pointer (may be NULL if len=0).
len Payload length (0..8).
Returns
0 on success, <0 on error.
Definition at line 313 of file canopen_space.c.
References g_ctx, canopen_space_ctx_t::last_tx_id, canopen_space_ctx_t::send, and canopen_space_ctx_t::send_user.
Referenced by canopen_space_sdo_write_u32(), and cia402_send_nmt().
canopen_space_start()
int canopen_space_start (void)
Start the stack services depending on role.
For ACTUATOR role this typically starts RPDO/TPDO objects and transitions NMT states (Reset comm -> Pre-op -> Operational). For MASTER role it performs minimal local NMT init (implementation-defined).
Returns
0 on success, <0 on error.
Definition at line 199 of file canopen_space.c.
References CO_ROLE_ACTUATOR, canopen_space_ctx_t::dev, g_ctx, canopen_space_ctx_t::net, canopen_space_ctx_t::nmt, canopen_space_ctx_t::role, canopen_space_ctx_t::rpdo1, and canopen_space_ctx_t::tpdo1.
canopen_space_tick_1ms()
void canopen_space_tick_1ms (void)
Advance stack time by 1 ms (must be called every 1 ms).
Updates internal timespec and calls can_net_set_time(). This is critical on bare-metal targets without POSIX clocks.
Definition at line 222 of file canopen_space.c.
References canopen_space_ctx_t::fail_code, g_ctx, canopen_space_ctx_t::net, time_add_1ms(), and canopen_space_ctx_t::ts.
canopen_space_tpdo1()
co_tpdo_t* canopen_space_tpdo1 (void)
Get pointer to TPDO1 (actuator role).
Returns
TPDO1 pointer or NULL if not created.
Definition at line 350 of file canopen_space.c.
References g_ctx, and canopen_space_ctx_t::tpdo1.
Referenced by cia402_actuator_pdo_push_tpdo1_to_od_and_send().
die()
static void die (uint32_t code) static
Trap into a fatal error state (debug helper).
Parameters
code Custom failure code stored in g_ctx.fail_code.
Definition at line 13 of file canopen_space.c.
References canopen_space_ctx_t::fail_code, and g_ctx.
Referenced by canopen_space_init().
od_init_for_role()
static co_dev_t* od_init_for_role (canopen_space_role_t role) static
Initialize the OD depending on role (master vs actuator).
Parameters
role canopen_space role
Returns
co_dev_t* pointer to initialized OD or NULL.
Definition at line 26 of file canopen_space.c.
References CO_ROLE_ACTUATOR.
Referenced by canopen_space_init().
pdo_config_slave_runtime()
static void pdo_config_slave_runtime (co_dev_t * dev, uint8_t node_id) static
Configure PDO mapping for ACTUATOR at runtime (RPDO1 and TPDO1).
This sets:
TPDO1 COB-ID = 0x180 + node, mapping: 0x6041:16 + 0x6064:32, event-driven
RPDO1 COB-ID = 0x200 + node, mapping: 0x6040:16 + 0x607A:32
Parameters
dev Object Dictionary.
node_id Local node id used to compute COB-IDs.
Definition at line 89 of file canopen_space.c.
Referenced by canopen_space_init().
time_add_1ms()
static void time_add_1ms (struct timespec * ts) static
Add 1ms to timespec (bare-metal timebase).
Parameters
ts Timespec to update.
Definition at line 38 of file canopen_space.c.
Referenced by canopen_space_tick_1ms().
Variable Documentation
g_ctx
canopen_space_ctx_t g_ctx = {0} static
Definition at line 7 of file canopen_space.c.
Referenced by can_send_func(), canopen_space_dev(), canopen_space_init(), canopen_space_nmt(), canopen_space_on_rx(), canopen_space_rpdo1(), canopen_space_send_raw(), canopen_space_start(), canopen_space_tick_1ms(), canopen_space_tpdo1(), and die().