ESA CANopen Docs: inc/cia402_wrapper.h File Reference
cia402_wrapper.h File Reference
Minimal CiA-402 helper wrapper for RPDO1/TPDO1 (master + actuator roles).
#include "canopen_space.h"
Data Structures
struct cia402_regs_t
Simple register bank for CiA-402 RPDO1/TPDO1 exchange.
Functions
int cia402_send_nmt (uint8_t cs, uint8_t node_id, uint8_t bus_id)
Send an NMT command (COB-ID 0x000).
void cia402_master_set_node_bus (uint8_t node_id, uint8_t bus_id)
Configure master target node_id and bus_id used for RPDO/TPDO handling.
void cia402_master_set_controlword (uint16_t cw)
Set master-side Controlword (0x6040:00).
void cia402_master_set_target_pos (int32_t pos)
Set master-side Target position (0x607A:00).
uint16_t cia402_master_get_controlword (void)
Get master-side cached Controlword (0x6040:00).
int32_t cia402_master_get_target_pos (void)
Get master-side cached Target position (0x607A:00).
int cia402_master_pdo_flush_rpdo1 (void)
Transmit RPDO1 (0x200 + node): 0x6040:16 + 0x607A:32.
void cia402_master_pdo_parse_tpdo1 (uint32_t cob_id, const uint8_t *data, uint8_t len)
Parse TPDO1 (0x180 + node) into master registers.
uint16_t cia402_master_get_statusword (void)
Get last parsed Statusword (0x6041:00) on master side.
int32_t cia402_master_get_pos_actual (void)
Get last parsed Position actual value (0x6064:00) on master side.
void cia402_actuator_set_node_bus (uint8_t node_id, uint8_t bus_id)
Configure actuator node_id and bus_id (stored for completeness).
void cia402_actuator_pdo_pull_rpdo1_from_od (uint32_t ms)
Pull RPDO1-mapped objects from Object Dictionary into actuator registers.
void cia402_actuator_set_statusword (uint16_t sw)
Set actuator-side Statusword (0x6041:00) to be published via TPDO1.
void cia402_actuator_set_pos_actual (int32_t pos)
Set actuator-side Position actual value (0x6064:00) to be published via TPDO1.
void cia402_actuator_pdo_push_tpdo1_to_od_and_send (void)
Push TPDO1-mapped objects into OD and trigger TPDO1 event.
uint16_t cia402_actuator_get_controlword (void)
(Optional) Get actuator-side cached Controlword (0x6040:00).
int32_t cia402_actuator_get_target_pos (void)
(Optional) Get actuator-side cached Target position (0x607A:00).
Detailed Description
Minimal CiA-402 helper wrapper for RPDO1/TPDO1 (master + actuator roles).
This wrapper maintains two register sets:
MASTER side registers (commands + feedback parsed from TPDO1),
ACTUATOR side registers (commands pulled from OD + feedback pushed to OD/TPDO1).
Intended mapping:
RPDO1 (Master -> Actuator): 0x6040:16 (Controlword) + 0x607A:32 (Target position)
TPDO1 (Actuator -> Master): 0x6041:16 (Statusword) + 0x6064:32 (Position actual)
The transport uses canopen_space helpers:
Raw CAN send for master RPDO/NMT,
Lely OD access + TPDO event trigger for actuator.
Definition in file cia402_wrapper.h.
Function Documentation
cia402_actuator_get_controlword()
uint16_t cia402_actuator_get_controlword (void)
(Optional) Get actuator-side cached Controlword (0x6040:00).
Returns
Controlword value.
Definition at line 201 of file cia402_wrapper.c.
References cia402_regs_t::controlword, and g_a.
Referenced by actuator_slave_get_controlword(), and actuator_slave_rx_update().
cia402_actuator_get_target_pos()
int32_t cia402_actuator_get_target_pos (void)
(Optional) Get actuator-side cached Target position (0x607A:00).
Returns
Target position value.
Definition at line 209 of file cia402_wrapper.c.
References g_a, and cia402_regs_t::target_pos.
Referenced by actuator_slave_get_target_pos(), and actuator_slave_rx_update().
cia402_actuator_pdo_pull_rpdo1_from_od()
void cia402_actuator_pdo_pull_rpdo1_from_od (uint32_t ms)
Pull RPDO1-mapped objects from Object Dictionary into actuator registers.
Reads:
0x6040:00 -> controlword
0x607A:00 -> target_pos
Parameters
ms Current time in milliseconds (stored in last_rx_ms).
Definition at line 240 of file cia402_wrapper.c.
References canopen_space_dev(), cia402_regs_t::controlword, g_a, cia402_regs_t::last_rx_ms, and cia402_regs_t::target_pos.
Referenced by actuator_slave_rx_update().
cia402_actuator_pdo_push_tpdo1_to_od_and_send()
void cia402_actuator_pdo_push_tpdo1_to_od_and_send (void)
Push TPDO1-mapped objects into OD and trigger TPDO1 event.
Writes:
0x6064:00 <- pos_actual
0x6041:00 <- statusword Then triggers TPDO1 event via co_tpdo_event().
Definition at line 261 of file cia402_wrapper.c.
References canopen_space_dev(), canopen_space_tpdo1(), g_a, cia402_regs_t::pos_actual, and cia402_regs_t::statusword.
Referenced by actuator_slave_tx_update().
cia402_actuator_set_node_bus()
void cia402_actuator_set_node_bus (uint8_t node_id, uint8_t bus_id)
Configure actuator node_id and bus_id (stored for completeness).
Parameters
node_id Local node ID.
bus_id Bus identifier used by canopen_space.
Definition at line 192 of file cia402_wrapper.c.
References cia402_regs_t::bus_id, g_a, and cia402_regs_t::node_id.
cia402_actuator_set_pos_actual()
void cia402_actuator_set_pos_actual (int32_t pos)
Set actuator-side Position actual value (0x6064:00) to be published via TPDO1.
Parameters
pos Actual position value.
Definition at line 226 of file cia402_wrapper.c.
References g_a, and cia402_regs_t::pos_actual.
Referenced by actuator_slave_set_pos_actual(), and actuator_slave_tx_update().
cia402_actuator_set_statusword()
void cia402_actuator_set_statusword (uint16_t sw)
Set actuator-side Statusword (0x6041:00) to be published via TPDO1.
Parameters
sw Statusword value.
Definition at line 217 of file cia402_wrapper.c.
References g_a, and cia402_regs_t::statusword.
Referenced by actuator_slave_set_statusword(), and actuator_slave_tx_update().
cia402_master_get_controlword()
uint16_t cia402_master_get_controlword (void)
Get master-side cached Controlword (0x6040:00).
Returns
Controlword value.
Definition at line 115 of file cia402_wrapper.c.
References cia402_regs_t::controlword, and g_m.
Referenced by actuator_master_get_controlword().
cia402_master_get_pos_actual()
int32_t cia402_master_get_pos_actual (void)
Get last parsed Position actual value (0x6064:00) on master side.
Returns
Actual position.
Definition at line 139 of file cia402_wrapper.c.
References g_m, and cia402_regs_t::pos_actual.
Referenced by actuator_master_get_pos_actual(), and actuator_master_rx_update().
cia402_master_get_statusword()
uint16_t cia402_master_get_statusword (void)
Get last parsed Statusword (0x6041:00) on master side.
Returns
Statusword.
Definition at line 131 of file cia402_wrapper.c.
References g_m, and cia402_regs_t::statusword.
Referenced by actuator_master_get_statusword(), and actuator_master_rx_update().
cia402_master_get_target_pos()
int32_t cia402_master_get_target_pos (void)
Get master-side cached Target position (0x607A:00).
Returns
Target position value.
Definition at line 123 of file cia402_wrapper.c.
References g_m, and cia402_regs_t::target_pos.
Referenced by actuator_master_get_target_pos().
cia402_master_pdo_flush_rpdo1()
int cia402_master_pdo_flush_rpdo1 (void)
Transmit RPDO1 (0x200 + node): 0x6040:16 + 0x607A:32.
Payload format (6 bytes):
bytes 0..1: Controlword (little-endian)
bytes 2..5: Target position (little-endian)
Returns
0 on success, <0 on error.
Definition at line 152 of file cia402_wrapper.c.
References g_m, and cia402_regs_t::node_id.
Referenced by actuator_master_tx_update().
cia402_master_pdo_parse_tpdo1()
void cia402_master_pdo_parse_tpdo1 (uint32_t cob_id, const uint8_t * data, uint8_t len)
Parse TPDO1 (0x180 + node) into master registers.
Expects at least 6 bytes payload:
bytes 0..1: Statusword (little-endian)
bytes 2..5: Position actual (little-endian)
Parameters
cob_id CAN identifier (COB-ID).
data Payload pointer.
len Payload length.
Definition at line 173 of file cia402_wrapper.c.
References g_m, le_i32(), le_u16(), cia402_regs_t::node_id, cia402_regs_t::pos_actual, and cia402_regs_t::statusword.
Referenced by actuator_master_rx_update().
cia402_master_set_controlword()
void cia402_master_set_controlword (uint16_t cw)
Set master-side Controlword (0x6040:00).
Parameters
cw Controlword value.
Definition at line 99 of file cia402_wrapper.c.
References cia402_regs_t::controlword, and g_m.
Referenced by actuator_master_set_controlword().
cia402_master_set_node_bus()
void cia402_master_set_node_bus (uint8_t node_id, uint8_t bus_id)
Configure master target node_id and bus_id used for RPDO/TPDO handling.
Parameters
node_id Target node ID.
bus_id Bus identifier used by canopen_space.
Definition at line 90 of file cia402_wrapper.c.
References cia402_regs_t::bus_id, g_m, and cia402_regs_t::node_id.
cia402_master_set_target_pos()
void cia402_master_set_target_pos (int32_t pos)
Set master-side Target position (0x607A:00).
Parameters
pos Target position value.
Definition at line 107 of file cia402_wrapper.c.
References g_m, and cia402_regs_t::target_pos.
Referenced by actuator_master_set_target_pos().
cia402_send_nmt()
int cia402_send_nmt (uint8_t cs, uint8_t node_id, uint8_t bus_id)
Send an NMT command (COB-ID 0x000).
Builds a 2-byte payload: [cs, node_id] and sends it via canopen_space_send_raw().
Parameters
cs NMT command specifier (e.g. Start/Stop/Reset node).
node_id Destination node (0 = broadcast).
bus_id Bus identifier used by canopen_space.
Returns
0 on success, <0 on error.
Definition at line 78 of file cia402_wrapper.c.
References canopen_space_send_raw().